runtime: nodejs10 # For Node.js 8, use runtime: nodejs8

instance_class: F2

env_variables:
  PROJECT_ID: u4dvgl32
  DATASET: production

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
